### ISSUE TITLE
[bug]Can't search correctly in Chinese

### ISSUE THREAD

**Issue by sherlockHlb** [Jakhes/extra_search_mod#1]
![)}BP~J~1_0{A96E$ZG_ R2](https://github.com/Jakhes/extra_search_mod/assets/30238046/ffca948b-0076-4391-addc-1165d34fa970) ![9VLI_{`P~0W9I6HQG{ RFWQ](https://github.com/Jakhes/extra_search_mod/assets/30238046/b8e6a8d7-3a84-4bed-9b41-ac2b32bd04fd) ![image](https://github.com/Jakhes/extra_search_mod/assets/30238046/32237242-6e51-464d-9e6e-b8b37fb31277)

This is a BUG, the normal search cannot be performed according to the full name, in Chinese
Similar to this, for example, "Composter" is called "堆肥" in Chinese, if I search for "堆", the correct result cannot be displayed, but irrelevant results are displayed, as shown in Figure 3
If I search for "肥", the results are displayed correctly. 

very strange error。
A similar error is also with flour（面粉）。。。
There are a few others, but I can't remember them

**Comment by Jakhes** [comment]
I think I've found the cause.
When writing a word into the search field that requires you to press the F Key, it will change the searchmode.
So my guess would be that when typing "堆" it uses the F Key equivalent on a Chinese keyboard.
I will need to change how to switch between the titlesearch and descriptionsearch so this doesn't happen.
Let me see what i can do ^^
Thanks for giving such a helpful bug report :)
